# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=200)),
                ('team_home', models.CharField(max_length=200)),
                ('team_away', models.CharField(max_length=200)),
                ('bet_home', models.FloatField()),
                ('bet_draw', models.FloatField()),
                ('bet_away', models.FloatField()),
            ],
        ),
    ]
